########################################################################################################
#            This file contains thresholds for a Google benchmark performance data changes             #
########################################################################################################

defaults:
  latency_per_op: 0.2  # 20%
  latency_per_op_mean: 0.2  # 20%
  latency_per_op_median: 0.2  # 20%
  latency_per_op_stddev: 0.2  # 20%

########################################################################################################
# Overrides support the following structure
########################################################################################################
#
# overrides:
#   resmoke_suite_name_1:
#     metric_name_1:
#     metric_name_2:
#   resmoke_suite_name_2:
#     metric_name_3:
#     metric_name_4:
#     metric_name_5:
#
########################################################################################################

overrides:
  benchmarks:
  benchmarks_sharding:
  benchmarks_bsoncolumn:
  # Disabled under SERVER-64949.
  # benchmarks_cst:
